### ISSUE TITLE
Odpisz na mój email.

### ISSUE THREAD

**Issue by playsenge** [KM127PL/KBOT-Rewrite#1]
Proszę.
Wiem co myślisz.
Ale prosze, poczekaj 30 sekund.
I am forever grateful.

**Comment by KM127PL** [comment]
Yeah,
That's also gonna be a no from me, sorry.

- 4307fea281eb8bee85f9a67cbc4a072cc25fe8128d3ac66a539d1febda80ea2a

**Comment by KM127PL** [comment]
Further response to this misery was attached in [this email](https://gist.github.com/KM127PL/4828069ec69100656954b0b9563b8e55)
